export const seedPassword = process.env.COMPANYPLAN_SEED_PASSWORD ?? "CompanyPlan@2026";

export const projectNameOptions = [
  { id: "pn-neon-chef", name: "Neon Chef 试玩 - p1" },
  { id: "pn-merge-manor", name: "Merge Manor A/B - p2" },
  { id: "pn-zombie-rush", name: "Zombie Rush Lite - p3" },
  { id: "pn-farm-merge", name: "Farm Merge 4D - p4" },
  { id: "pn-pet-salon", name: "Pet Salon Quest - p5" },
  { id: "pn-idle-miner", name: "Idle Miner Sprint - p6" },
  { id: "pn-puzzle-cruise", name: "Puzzle Cruise - p7" },
  { id: "pn-royal-room", name: "Royal Room Rescue - p8" },
];

export const ticketTypeSettings = [
  { typeKey: "美术", label: "美术", defaultDeliveryHours: 36, riskWarningHours: 8 },
  { typeKey: "UI", label: "UI", defaultDeliveryHours: 24, riskWarningHours: 6 },
  { typeKey: "模型", label: "模型", defaultDeliveryHours: 48, riskWarningHours: 12 },
  { typeKey: "动画", label: "动画", defaultDeliveryHours: 40, riskWarningHours: 10 },
  { typeKey: "研发", label: "研发", defaultDeliveryHours: 32, riskWarningHours: 8 },
  { typeKey: "音效", label: "音效", defaultDeliveryHours: 16, riskWarningHours: 4 },
];

export const people = [
  {
    id: "u-admin",
    username: "admin",
    name: "林知远",
    roleKey: "admin",
    title: "运营管理员",
    discipline: "管理",
    capacity: 72,
    completion: 93,
    projectIds: ["p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8"],
  },
  {
    id: "u-producer",
    username: "producer",
    name: "周牧",
    roleKey: "producer",
    title: "项目负责人",
    discipline: "项目",
    capacity: 88,
    completion: 81,
    projectIds: ["p1", "p2", "p3", "p7"],
  },
  {
    id: "u-artist",
    username: "artist",
    name: "陈岚",
    roleKey: "artist",
    title: "美术主设",
    discipline: "美术",
    capacity: 91,
    completion: 76,
    projectIds: ["p1", "p4", "p6", "p8"],
  },
  {
    id: "u-ui",
    username: "ui",
    name: "何苗",
    roleKey: "ui",
    title: "UI 设计",
    discipline: "UI",
    capacity: 84,
    completion: 86,
    projectIds: ["p1", "p2", "p5", "p8"],
  },
  {
    id: "u-model",
    username: "model",
    name: "顾远",
    roleKey: "model",
    title: "3D 模型",
    discipline: "模型",
    capacity: 96,
    completion: 69,
    projectIds: ["p1", "p3", "p4", "p6"],
  },
  {
    id: "u-model-2",
    username: "model2",
    name: "陆承",
    roleKey: "model",
    title: "3D 模型",
    discipline: "模型",
    capacity: 78,
    completion: 84,
    projectIds: ["p1", "p3"],
  },
  {
    id: "u-animator",
    username: "animator",
    name: "许遥",
    roleKey: "animator",
    title: "动画设计",
    discipline: "动画",
    capacity: 79,
    completion: 88,
    projectIds: ["p1", "p5", "p7", "p8"],
  },
  {
    id: "u-dev",
    username: "dev",
    name: "姜北",
    roleKey: "programmer",
    title: "Playable 开发",
    discipline: "研发",
    capacity: 87,
    completion: 82,
    projectIds: ["p1", "p2", "p6", "p7"],
  },
  {
    id: "u-sound",
    username: "sound",
    name: "宋栖",
    roleKey: "artist",
    title: "音效剪辑",
    discipline: "音效",
    capacity: 63,
    completion: 91,
    projectIds: ["p3", "p4", "p5"],
  },
];

export const projects = [
  {
    id: "p1",
    name: "Neon Chef 试玩",
    client: "TopJoy Games",
    genre: "烹饪经营",
    channel: "Meta / TikTok",
    ownerId: "u-producer",
    status: "制作中",
    phase: "素材合流",
    health: "amber",
    progress: 68,
    dueInDays: 6,
    ticketCount: 34,
    openTicketCount: 11,
    teamIds: ["u-producer", "u-artist", "u-ui", "u-model", "u-model-2", "u-animator", "u-dev"],
    disciplineProgress: { 美术: 72, UI: 80, 模型: 58, 动画: 64, 研发: 66, 音效: 20 },
    blocker: "模型低模包延迟，影响 6 个动画状态机",
  },
  {
    id: "p2",
    name: "Merge Manor A/B",
    client: "River Studio",
    genre: "合成装修",
    channel: "Applovin",
    ownerId: "u-producer",
    status: "制作中",
    phase: "交互开发",
    health: "green",
    progress: 82,
    dueInDays: 3,
    ticketCount: 27,
    openTicketCount: 5,
    teamIds: ["u-producer", "u-ui", "u-dev"],
    disciplineProgress: { 美术: 88, UI: 90, 模型: 0, 动画: 76, 研发: 78, 音效: 65 },
    blocker: "无",
  },
  {
    id: "p3",
    name: "Zombie Rush Lite",
    client: "ArcMint",
    genre: "塔防射击",
    channel: "Unity Ads",
    ownerId: "u-producer",
    status: "排期中",
    phase: "玩法拆解",
    health: "amber",
    progress: 34,
    dueInDays: 12,
    ticketCount: 18,
    openTicketCount: 9,
    teamIds: ["u-producer", "u-model", "u-model-2", "u-sound"],
    disciplineProgress: { 美术: 42, UI: 24, 模型: 30, 动画: 22, 研发: 15, 音效: 55 },
    blocker: "客户脚本未确认，紧急开场镜头缺参考",
  },
  {
    id: "p4",
    name: "Farm Merge 4D",
    client: "Mocha Lab",
    genre: "合成农场",
    channel: "Meta",
    ownerId: "u-admin",
    status: "制作中",
    phase: "视觉定稿",
    health: "red",
    progress: 51,
    dueInDays: -2,
    ticketCount: 39,
    openTicketCount: 17,
    teamIds: ["u-artist", "u-model", "u-sound"],
    disciplineProgress: { 美术: 48, UI: 36, 模型: 44, 动画: 35, 研发: 20, 音效: 62 },
    blocker: "核心角色重设，已影响首版交付",
  },
  {
    id: "p5",
    name: "Pet Salon Quest",
    client: "NorthPlay",
    genre: "宠物养成",
    channel: "TikTok",
    ownerId: "u-admin",
    status: "待验收",
    phase: "QA 验收",
    health: "green",
    progress: 91,
    dueInDays: 1,
    ticketCount: 31,
    openTicketCount: 4,
    teamIds: ["u-ui", "u-animator", "u-sound"],
    disciplineProgress: { 美术: 95, UI: 92, 模型: 0, 动画: 88, 研发: 84, 音效: 93 },
    blocker: "无",
  },
  {
    id: "p6",
    name: "Idle Miner Sprint",
    client: "BlueTap",
    genre: "放置采矿",
    channel: "Google UAC",
    ownerId: "u-admin",
    status: "制作中",
    phase: "首版联调",
    health: "amber",
    progress: 59,
    dueInDays: 8,
    ticketCount: 22,
    openTicketCount: 8,
    teamIds: ["u-artist", "u-model", "u-dev"],
    disciplineProgress: { 美术: 66, UI: 52, 模型: 62, 动画: 40, 研发: 58, 音效: 0 },
    blocker: "资源命名规范未统一，联调返工较多",
  },
  {
    id: "p7",
    name: "Puzzle Cruise",
    client: "SailFox",
    genre: "三消冒险",
    channel: "Meta / Mintegral",
    ownerId: "u-producer",
    status: "制作中",
    phase: "动画打磨",
    health: "green",
    progress: 74,
    dueInDays: 7,
    ticketCount: 25,
    openTicketCount: 7,
    teamIds: ["u-producer", "u-animator", "u-dev"],
    disciplineProgress: { 美术: 85, UI: 79, 模型: 0, 动画: 71, 研发: 70, 音效: 62 },
    blocker: "无",
  },
  {
    id: "p8",
    name: "Royal Room Rescue",
    client: "Olive Games",
    genre: "找茬解谜",
    channel: "TikTok",
    ownerId: "u-admin",
    status: "立项",
    phase: "需求确认",
    health: "amber",
    progress: 19,
    dueInDays: 16,
    ticketCount: 12,
    openTicketCount: 10,
    teamIds: ["u-artist", "u-ui", "u-animator"],
    disciplineProgress: { 美术: 18, UI: 26, 模型: 0, 动画: 10, 研发: 0, 音效: 0 },
    blocker: "素材版权清单待客户回传",
  },
];

export const tickets = [
  {
    id: "UI-2406-066",
    title: "主界面 3D 图标补模型",
    sourceProjectName: "小主厨解锁餐厅 - ttwj",
    projectId: "p1",
    requesterId: "u-ui",
    ownerId: "u-model",
    discipline: "模型",
    startAt: "2026/06/12 16:20",
    status: "排队中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "模型",
    summary: "UI 侧需要一个低面数 3D 餐厅图标，供主界面入口使用。",
    hyperlink: null,
    text: "我提给模型同事",
    attachments: [{ name: "icon_blockout.png", kind: "图片", size: "680 KB" }],
  },
  {
    id: "MODEL-2406-070",
    title: "同岗位模型师道具低模",
    sourceProjectName: "Zombie Rush Lite - p3",
    projectId: "p3",
    requesterId: "u-admin",
    ownerId: "u-model-2",
    discipline: "模型",
    startAt: "2026/06/12 15:10",
    status: "进行中",
    priority: "普通",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "模型",
    summary: "给另一位模型师的道具低模任务，不能被顾远仅因同岗位看到。",
    hyperlink: null,
    text: "同岗位隔离验证",
    attachments: [{ name: "prop_blockout.png", kind: "图片", size: "540 KB" }],
  },
  {
    id: "UI-2406-065",
    title: "截图",
    sourceProjectName: "陨石袭击野牛冲撞塔防版 - fnd",
    projectId: "p1",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 14:33",
    status: "进行中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "UI",
    summary: "按新版本玩法补充截图素材，供同事对照制作。",
    hyperlink: "https://www.kdocs.cn/l/cqJCOLkt7Na0",
    text: "参考图优先级高",
    attachments: [{ name: "ui_ref_screenshot.png", kind: "图片", size: "1.2 MB" }],
  },
  {
    id: "UI-2406-064",
    title: "多语言 + 截图",
    sourceProjectName: "回收子弹 - fnd",
    projectId: "p3",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 13:30",
    status: "进行中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "UI",
    summary: "多语言文案、按钮和界面截图一起补齐。",
    hyperlink: null,
    text: "先出英文和中文",
    attachments: [{ name: "language_pack.xlsx", kind: "文件", size: "86 KB" }],
  },
  {
    id: "UI-2406-063",
    title: "资源入库",
    sourceProjectName: "选国家发展 - mars",
    projectId: "p4",
    requesterId: "u-admin",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/11 13:01",
    status: "进行中",
    priority: "优先",
    ageDays: 1,
    statusAgeDays: 1,
    dueInDays: 2,
    needType: "UI",
    summary: "整理国家选择、发展阶段相关 UI 资产并入库。",
    hyperlink: null,
    text: "截图参考表第 1 行",
    attachments: [{ name: "country_ui_ref.png", kind: "图片", size: "930 KB" }],
  },
  {
    id: "REQ-2406-120",
    title: "交互点击区修正",
    sourceProjectName: "Neon Chef 试玩 - p1",
    projectId: "p1",
    requesterId: "u-ui",
    ownerId: "u-dev",
    discipline: "研发",
    startAt: "2026/06/12 09:30",
    status: "进行中",
    priority: "紧急",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 1,
    needType: "研发联调",
    summary: "根据 UI 标注修正点击热区、引导遮罩和失败页跳转。",
    hyperlink: "svn://47.101.191.213:3690/playableAssets",
    text: "紧急联调需求",
    attachments: [{ name: "click_area_note.png", kind: "图片", size: "740 KB" }],
  },
  {
    id: "REQ-2406-121",
    title: "角色减面",
    sourceProjectName: "Farm Merge 4D - p4",
    projectId: "p4",
    requesterId: "u-producer",
    ownerId: "u-artist",
    discipline: "美术",
    startAt: "2026/06/10 10:05",
    status: "阻塞",
    priority: "紧急",
    ageDays: 6,
    statusAgeDays: 3,
    dueInDays: -1,
    needType: "美术",
    summary: "根据试玩包体限制压缩角色面数，保留主视角识别度。",
    hyperlink: null,
    text: "等待客户确认参考",
    attachments: [{ name: "character_ref.zip", kind: "附件", size: "8.4 MB" }],
  },
  {
    id: "REQ-2406-122",
    title: "入场动画调整",
    sourceProjectName: "Puzzle Cruise - p7",
    projectId: "p7",
    requesterId: "u-ui",
    ownerId: "u-animator",
    discipline: "动画",
    startAt: "2026/06/11 15:30",
    status: "进行中",
    priority: "优先",
    ageDays: 1,
    statusAgeDays: 1,
    dueInDays: 2,
    needType: "动画",
    summary: "调整入场节奏、暂停点和按钮出现时间，配合首屏引导。",
    hyperlink: null,
    text: "需同步给研发",
    attachments: [],
  },
  {
    id: "REQ-2406-123",
    title: "音效替换",
    sourceProjectName: "Zombie Rush Lite - p3",
    projectId: "p3",
    requesterId: "u-producer",
    ownerId: "u-sound",
    discipline: "音效",
    startAt: "2026/06/09 11:05",
    status: "已完成",
    priority: "低优先",
    ageDays: 3,
    statusAgeDays: 1,
    dueInDays: 0,
    needType: "音效",
    summary: "替换点击、奖励、失败和转场音效，保持平台音量一致。",
    hyperlink: null,
    text: "已同步到资产库",
    attachments: [{ name: "sfx_pack.wav", kind: "文件", size: "2.6 MB" }],
  },
];
