import type { Discipline, Person, Project, Ticket, TicketStatus } from "../../types";

export const people: Person[] = [
  {
    id: "u-admin",
    name: "林知远",
    roleKey: "admin",
    title: "运营管理员",
    discipline: "管理",
    capacity: 72,
    completion: 93,
    projectIds: ["p1", "p2", "p3", "p4", "p5", "p6", "p7", "p8"],
  },
  {
    id: "u-producer",
    name: "周牧",
    roleKey: "producer",
    title: "项目负责人",
    discipline: "项目",
    capacity: 88,
    completion: 81,
    projectIds: ["p1", "p2", "p3", "p7"],
  },
  {
    id: "u-artist",
    name: "陈岚",
    roleKey: "artist",
    title: "美术主设",
    discipline: "美术",
    capacity: 91,
    completion: 76,
    projectIds: ["p1", "p4", "p6", "p8"],
  },
  {
    id: "u-ui",
    name: "何苗",
    roleKey: "ui",
    title: "UI 设计",
    discipline: "UI",
    capacity: 84,
    completion: 86,
    projectIds: ["p1", "p2", "p5", "p8"],
  },
  {
    id: "u-model",
    name: "顾远",
    roleKey: "model",
    title: "3D 模型",
    discipline: "模型",
    capacity: 96,
    completion: 69,
    projectIds: ["p1", "p3", "p4", "p6"],
  },
  {
    id: "u-model-2",
    name: "陆承",
    roleKey: "model",
    title: "3D 模型",
    discipline: "模型",
    capacity: 78,
    completion: 84,
    projectIds: ["p1", "p3"],
  },
  {
    id: "u-animator",
    name: "许遥",
    roleKey: "animator",
    title: "动画设计",
    discipline: "动画",
    capacity: 79,
    completion: 88,
    projectIds: ["p1", "p5", "p7", "p8"],
  },
  {
    id: "u-dev",
    name: "姜北",
    roleKey: "programmer",
    title: "Playable 开发",
    discipline: "研发",
    capacity: 87,
    completion: 82,
    projectIds: ["p1", "p2", "p6", "p7"],
  },
  {
    id: "u-sound",
    name: "宋栖",
    roleKey: "artist",
    title: "音效剪辑",
    discipline: "音效",
    capacity: 63,
    completion: 91,
    projectIds: ["p3", "p4", "p5"],
  },
];

export const initialProjects: Project[] = [
  {
    id: "p1",
    name: "Neon Chef 试玩",
    client: "TopJoy Games",
    genre: "烹饪经营",
    channel: "Meta / TikTok",
    ownerId: "u-producer",
    status: "制作中",
    phase: "素材合流",
    health: "amber",
    progress: 68,
    dueInDays: 6,
    ticketCount: 34,
    openTicketCount: 11,
    teamIds: ["u-producer", "u-artist", "u-ui", "u-model", "u-model-2", "u-animator", "u-dev"],
    disciplineProgress: { 美术: 72, UI: 80, 模型: 58, 动画: 64, 研发: 66, 音效: 20 },
    blocker: "模型低模包延迟，影响 6 个动画状态机",
  },
  {
    id: "p2",
    name: "Merge Manor A/B",
    client: "River Studio",
    genre: "合成装修",
    channel: "Applovin",
    ownerId: "u-producer",
    status: "制作中",
    phase: "交互开发",
    health: "green",
    progress: 82,
    dueInDays: 3,
    ticketCount: 27,
    openTicketCount: 5,
    teamIds: ["u-producer", "u-ui", "u-dev"],
    disciplineProgress: { 美术: 88, UI: 90, 模型: 0, 动画: 76, 研发: 78, 音效: 65 },
    blocker: "无",
  },
  {
    id: "p3",
    name: "Zombie Rush Lite",
    client: "ArcMint",
    genre: "塔防射击",
    channel: "Unity Ads",
    ownerId: "u-producer",
    status: "排期中",
    phase: "玩法拆解",
    health: "amber",
    progress: 34,
    dueInDays: 12,
    ticketCount: 18,
    openTicketCount: 9,
    teamIds: ["u-producer", "u-model", "u-model-2", "u-sound"],
    disciplineProgress: { 美术: 42, UI: 24, 模型: 30, 动画: 22, 研发: 15, 音效: 55 },
    blocker: "客户脚本未确认，紧急开场镜头缺参考",
  },
  {
    id: "p4",
    name: "Farm Merge 4D",
    client: "Mocha Lab",
    genre: "合成农场",
    channel: "Meta",
    ownerId: "u-admin",
    status: "制作中",
    phase: "视觉定稿",
    health: "red",
    progress: 51,
    dueInDays: -2,
    ticketCount: 39,
    openTicketCount: 17,
    teamIds: ["u-artist", "u-model", "u-sound"],
    disciplineProgress: { 美术: 48, UI: 36, 模型: 44, 动画: 35, 研发: 20, 音效: 62 },
    blocker: "核心角色重设，已影响首版交付",
  },
  {
    id: "p5",
    name: "Pet Salon Quest",
    client: "NorthPlay",
    genre: "宠物养成",
    channel: "TikTok",
    ownerId: "u-admin",
    status: "待验收",
    phase: "QA 验收",
    health: "green",
    progress: 91,
    dueInDays: 1,
    ticketCount: 31,
    openTicketCount: 4,
    teamIds: ["u-ui", "u-animator", "u-sound"],
    disciplineProgress: { 美术: 95, UI: 92, 模型: 0, 动画: 88, 研发: 84, 音效: 93 },
    blocker: "无",
  },
  {
    id: "p6",
    name: "Idle Miner Sprint",
    client: "BlueTap",
    genre: "放置采矿",
    channel: "Google UAC",
    ownerId: "u-admin",
    status: "制作中",
    phase: "首版联调",
    health: "amber",
    progress: 59,
    dueInDays: 8,
    ticketCount: 22,
    openTicketCount: 8,
    teamIds: ["u-artist", "u-model", "u-dev"],
    disciplineProgress: { 美术: 66, UI: 52, 模型: 62, 动画: 40, 研发: 58, 音效: 0 },
    blocker: "资源命名规范未统一，联调返工较多",
  },
  {
    id: "p7",
    name: "Puzzle Cruise",
    client: "SailFox",
    genre: "三消冒险",
    channel: "Meta / Mintegral",
    ownerId: "u-producer",
    status: "制作中",
    phase: "动画打磨",
    health: "green",
    progress: 74,
    dueInDays: 7,
    ticketCount: 25,
    openTicketCount: 7,
    teamIds: ["u-producer", "u-animator", "u-dev"],
    disciplineProgress: { 美术: 85, UI: 79, 模型: 0, 动画: 71, 研发: 70, 音效: 62 },
    blocker: "无",
  },
  {
    id: "p8",
    name: "Royal Room Rescue",
    client: "Olive Games",
    genre: "找茬解谜",
    channel: "TikTok",
    ownerId: "u-admin",
    status: "立项",
    phase: "需求确认",
    health: "amber",
    progress: 19,
    dueInDays: 16,
    ticketCount: 12,
    openTicketCount: 10,
    teamIds: ["u-artist", "u-ui", "u-animator"],
    disciplineProgress: { 美术: 18, UI: 26, 模型: 0, 动画: 10, 研发: 0, 音效: 0 },
    blocker: "素材版权清单待客户回传",
  },
];

const baseTickets: Ticket[] = [
  {
    id: "UI-2406-066",
    title: "主界面 3D 图标补模型",
    sourceProjectName: "小主厨解锁餐厅 - ttwj",
    projectId: "p1",
    requesterId: "u-ui",
    ownerId: "u-model",
    discipline: "模型",
    startAt: "2026/06/12 16:20",
    status: "排队中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "模型",
    summary: "UI 侧需要一个低面数 3D 餐厅图标，供主界面入口使用。",
    text: "我提给模型同事",
    attachments: [{ id: "att-ui-66-1", name: "icon_blockout.png", kind: "图片", size: "680 KB" }],
  },
  {
    id: "MODEL-2406-070",
    title: "同岗位模型师道具低模",
    sourceProjectName: "Zombie Rush Lite - p3",
    projectId: "p3",
    requesterId: "u-admin",
    ownerId: "u-model-2",
    discipline: "模型",
    startAt: "2026/06/12 15:10",
    status: "进行中",
    priority: "普通",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "模型",
    summary: "给另一位模型师的道具低模任务，不能被顾远仅因同岗位看到。",
    text: "同岗位隔离验证",
    attachments: [{ id: "att-model-70-1", name: "prop_blockout.png", kind: "图片", size: "540 KB" }],
  },
  {
    id: "UI-2406-065",
    title: "截图",
    sourceProjectName: "陨石袭击野牛冲撞塔防版 - fnd",
    projectId: "p1",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 14:33",
    status: "进行中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "UI",
    summary: "按新版本玩法补充截图素材，供同事对照制作。",
    hyperlink: "https://www.kdocs.cn/l/cqJCOLkt7Na0",
    text: "参考图优先级高",
    attachments: [
      { id: "att-ui-65-1", name: "ui_ref_screenshot.png", kind: "图片", size: "1.2 MB" },
    ],
  },
  {
    id: "UI-2406-064",
    title: "多语言 + 截图",
    sourceProjectName: "回收子弹 - fnd",
    projectId: "p3",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 13:30",
    status: "进行中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "UI",
    summary: "多语言文案、按钮和界面截图一起补齐。",
    text: "先出英文和中文",
    attachments: [{ id: "att-ui-64-1", name: "language_pack.xlsx", kind: "文件", size: "86 KB" }],
  },
  {
    id: "UI-2406-063",
    title: "资源入库",
    sourceProjectName: "选国家发展 - mars",
    projectId: "p4",
    requesterId: "u-admin",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/11 13:01",
    status: "进行中",
    priority: "优先",
    ageDays: 1,
    statusAgeDays: 1,
    dueInDays: 2,
    needType: "UI",
    summary: "整理国家选择、发展阶段相关 UI 资产并入库。",
    text: "截图参考表第 1 行",
    attachments: [
      { id: "att-ui-63-1", name: "country_ui_ref.png", kind: "图片", size: "930 KB" },
    ],
  },
  {
    id: "UI-2406-062",
    title: "按钮态和结算页截图",
    sourceProjectName: "部落冲突 - koa",
    projectId: "p2",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/11 14:06",
    status: "进行中",
    priority: "优先",
    ageDays: 1,
    statusAgeDays: 1,
    dueInDays: 2,
    needType: "UI",
    summary: "补齐战斗按钮态、结算弹窗和基础截图。",
    text: "需要和玩法镜头一致",
    attachments: [{ id: "att-ui-62-1", name: "clash_ui_refs.zip", kind: "文件", size: "8.5 MB" }],
  },
  {
    id: "UI-2406-061",
    title: "卖水杀敌 UI 调整",
    sourceProjectName: "卖水杀敌 - fnd",
    projectId: "p6",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/11 14:07",
    status: "进行中",
    priority: "优先",
    ageDays: 1,
    statusAgeDays: 1,
    dueInDays: 2,
    needType: "UI",
    summary: "补充售卖流程、杀敌反馈、道具按钮的界面图。",
    text: "注意尺寸统一",
  },
  {
    id: "UI-2406-060",
    title: "渠道包 UI 适配",
    sourceProjectName: "机动组_补渠道",
    projectId: "p1",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/11 15:05",
    status: "进行中",
    priority: "优先",
    ageDays: 1,
    statusAgeDays: 1,
    dueInDays: 2,
    needType: "UI",
    summary: "按新增渠道补全入口、落地页和 CTA 适配。",
    hyperlink: "svn://47.101.191.213:3690/uiRepo",
  },
  {
    id: "UI-2406-059",
    title: "截图与基础按钮",
    sourceProjectName: "608PA01 - dawnwatch",
    projectId: "p7",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 10:11",
    status: "进行中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "UI",
    summary: "补齐首屏截图和基础按钮态，供投放版使用。",
    attachments: [{ id: "att-ui-59-1", name: "dawnwatch_ui.png", kind: "图片", size: "1.6 MB" }],
  },
  {
    id: "UI-2406-058",
    title: "截图标注",
    sourceProjectName: "112A - jx",
    projectId: "p5",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 10:32",
    status: "进行中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "UI",
    summary: "按关卡流程补截图标注，明确弹窗和点击区域。",
    attachments: [{ id: "att-ui-58-1", name: "112a_note.png", kind: "图片", size: "720 KB" }],
  },
  {
    id: "UI-2406-057",
    title: "确认弹窗和失败页",
    sourceProjectName: "清洗菌毯 - fnd",
    projectId: "p8",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 13:30",
    status: "进行中",
    priority: "优先",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 2,
    needType: "UI",
    summary: "清洗流程的确认弹窗、失败页和重试按钮。",
    text: "参考表第 7 行",
  },
  {
    id: "UI-2406-056",
    title: "剧情选择页补图",
    sourceProjectName: "剧情不选择 - mt",
    projectId: "p3",
    requesterId: "u-producer",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 15:20",
    status: "排队中",
    priority: "普通",
    ageDays: 0,
    statusAgeDays: 0,
    dueInDays: 3,
    needType: "UI",
    summary: "剧情分支选择页补充不选择状态的按钮图。",
  },
  {
    id: "UI-2406-055",
    title: "老鼠针界面整理",
    sourceProjectName: "老鼠针 - zyy",
    projectId: "p4",
    requesterId: "u-admin",
    ownerId: "u-ui",
    discipline: "UI",
    startAt: "2026/06/12 16:00",
    status: "已完成",
    priority: "低优先",
    ageDays: 1,
    statusAgeDays: 1,
    dueInDays: 1,
    needType: "UI",
    summary: "整理完成，已同步到 UI 资产库。",
    attachments: [{ id: "att-ui-55-1", name: "mouse_needle_final.fig", kind: "文件", size: "3.4 MB" }],
  },
];

const scaledTicketTitles: Array<{
  title: string;
  discipline: Discipline;
  needType: string;
  ownerId: string;
  requesterId: string;
  summary: string;
}> = [
  {
    title: "资产入库",
    discipline: "模型",
    needType: "模型",
    ownerId: "u-model",
    requesterId: "u-producer",
    summary: "整理模型资产、贴图命名和入库目录，供后续动画与开发调用。",
  },
  {
    title: "按钮态补齐",
    discipline: "UI",
    needType: "UI",
    ownerId: "u-ui",
    requesterId: "u-producer",
    summary: "补齐普通、按下、不可点击和高亮状态，统一输出到 UI 资产库。",
  },
  {
    title: "角色减面",
    discipline: "美术",
    needType: "美术",
    ownerId: "u-artist",
    requesterId: "u-producer",
    summary: "根据试玩包体限制压缩角色面数，保留主视角识别度。",
  },
  {
    title: "入场动画调整",
    discipline: "动画",
    needType: "动画",
    ownerId: "u-animator",
    requesterId: "u-ui",
    summary: "调整入场节奏、暂停点和按钮出现时间，配合首屏引导。",
  },
  {
    title: "交互点击区修正",
    discipline: "研发",
    needType: "研发",
    ownerId: "u-dev",
    requesterId: "u-ui",
    summary: "根据 UI 标注修正点击热区、引导遮罩和失败页跳转。",
  },
  {
    title: "音效替换",
    discipline: "音效",
    needType: "音效",
    ownerId: "u-sound",
    requesterId: "u-producer",
    summary: "替换点击、奖励、失败和转场音效，保持平台音量一致。",
  },
  {
    title: "UI 截图标注",
    discipline: "UI",
    needType: "UI",
    ownerId: "u-ui",
    requesterId: "u-model",
    summary: "按最新流程补标注截图，说明模型资源在界面中的摆放比例。",
  },
  {
    title: "低模图标补做",
    discipline: "模型",
    needType: "模型",
    ownerId: "u-model",
    requesterId: "u-ui",
    summary: "补一个低面数图标模型，用于主界面入口和奖励弹窗。",
  },
];

const scaledSourceNames = [
  "甜品工厂 - fnd",
  "花园救援 - zyy",
  "小主厨解锁餐厅 - ttwj",
  "怪物冲刺 - mars",
  "太空温泉 - fnd",
  "消消乐餐厅 - mt",
  "合成小岛 - koa",
  "矿车大亨 - jx",
  "宠物美容院 - bzg",
  "国王房间逃脱 - twj",
  "清洗菌毯 - fnd",
  "回收子弹 - fnd",
];

const scaledStatuses: TicketStatus[] = [
  "排队中",
  "进行中",
  "进行中",
  "进行中",
  "进行中",
  "已完成",
  "阻塞",
  "进行中",
];

function createScaledTickets(count = 72): Ticket[] {
  return Array.from({ length: count }, (_, index) => {
    const template = scaledTicketTitles[index % scaledTicketTitles.length];
    const project = initialProjects[index % initialProjects.length];
    const status = scaledStatuses[index % scaledStatuses.length];
    const hasAttachment = index % 3 === 0;
    const hasLink = index % 5 === 0;
    const ageDays = status === "已完成" ? 1 + (index % 3) : index % 9;
    const statusAgeDays = status === "排队中" ? index % 4 : index % 6;

    return {
      id: `REQ-2406-${String(120 + index).padStart(3, "0")}`,
      title: template.title,
      sourceProjectName: scaledSourceNames[index % scaledSourceNames.length],
      projectId: project.id,
      requesterId: template.requesterId,
      ownerId: template.ownerId,
      discipline: template.discipline,
      startAt: `2026/06/${String(10 + (index % 3)).padStart(2, "0")} ${String(9 + (index % 9)).padStart(2, "0")}:${index % 2 === 0 ? "30" : "05"}`,
      status,
      priority: index % 11 === 0 ? "紧急" : index % 7 === 0 ? "低优先" : index % 4 === 0 ? "普通" : "优先",
      ageDays,
      statusAgeDays,
      dueInDays: status === "阻塞" ? -1 : 1 + (index % 5),
      needType: template.needType,
      summary: template.summary,
      hyperlink: hasLink ? "svn://47.101.191.213:3690/playableAssets" : undefined,
      text: index % 4 === 0 ? "需要同步给上下游确认" : index % 4 === 1 ? "参考上一版投放素材" : "-",
      attachments: hasAttachment
        ? [
            {
              id: `att-scaled-${index}`,
              name: `${template.needType.toLowerCase()}_ref_${index + 1}.png`,
              kind: index % 2 === 0 ? "图片" : index % 5 === 0 ? "文件" : "附件",
              size: `${680 + index * 12} KB`,
            },
          ]
        : undefined,
    };
  });
}

export const initialTickets: Ticket[] = [...baseTickets, ...createScaledTickets()];
